<?php  exit();
/*
Page: /uploads/dede/index_menu.php
Error: DedeCms错误警告：<font color='red'>连接数据库失败，可能数据库密码不对或数据库服务器出错！</font>
Time2015-08-18 21:27:57
*/
?>
<?php  exit();
/*
Page: /uploads/dede/index_menu.php
Error: DedeCms错误警告：<font color='red'>连接数据库失败，可能数据库密码不对或数据库服务器出错！</font>
Time2015-08-18 21:28:01
*/
?>
<?php  exit();
/*
Page: /uploads/dede/
Error: DedeCms错误警告：<font color='red'>连接数据库失败，可能数据库密码不对或数据库服务器出错！</font>
Time2015-08-18 21:28:22
*/
?>
<?php  exit();
/*
Page: /uploads/dede/login.php
Error: DedeCms错误警告：<font color='red'>连接数据库失败，可能数据库密码不对或数据库服务器出错！</font>
Time2015-08-18 21:35:52
*/
?>
<?php  exit();
/*
Page: /uploads/dede/login.php
Error: DedeCms错误警告：<font color='red'>连接数据库失败，可能数据库密码不对或数据库服务器出错！</font>
Time2015-08-22 13:30:58
*/
?>
